### PR TITLE
Typed Queue

### LINKED ISSUE #6: [Proposal] Typed Queue
I use in a Project the Collection Class with a Entity as Type. This work really good and is really straightforward. 
But i think a Queue (FIFO Principle) would match my needs even better.

Therefore, my consideration of whether it is a good extension for this project.
Is this a benefit for this Project?

### PR DESCRIPTION
**Pull request by zf2timo**
This PR resolves #6 by adding a typed Queue implementation.

### CODE REVIEW

**Comment by zf2timo** [comment]
@ramsey  can you please review the changes, if there is something missing.

**Comment by ramsey** [comment]
Sorry for the lack of response. Been busy this week. I'll review the PR soon and let you know if I think you should make any changes. Thanks!

**Comment by zf2timo** [comment]
@ramsey any news on this pr?

**Comment by ramsey** [comment]
Sorry for the delay. This looks great. Merging!

**Pull request merged**
