### PR TITLE
Patch generic collection (diff(), intersect() and merge())

### LINKED ISSUE #53: Cannot manipulate on Generic Collection
## Describe the bug

I don't know this is a bug or a feature, but it looks strange for me.

## To Reproduce...
I wrote a simple test case to reproduce the issue.

 ```php
    <?php

    public function testDiffGenericCollection(): void
    {
        $bar1 = new Bar(1, 'a');
        $bar2 = new Bar(2, 'b');

        $barCollection1 = new Collection(Bar::class);
        $barCollection2 = new Collection(Bar::class);

        //Add 1 element to $barCollection1
        $barCollection1->add($bar1);

        //Add 2 elements to $barCollection2
        $barCollection2->add($bar1);
        $barCollection2->add($bar2);

        $diffCollection = $barCollection1->diff($barCollection2);

        $this->assertNotSame($diffCollection, $barCollection1);
        $this->assertNotSame($diffCollection, $barCollection2);
        $this->assertEquals([$bar2], $diffCollection->toArray());

        // Make sure original collections are untouched
        $this->assertEquals([$bar1], $barCollection1->toArray());
        $this->assertEquals([$bar1, $bar2], $barCollection2->toArray());
    }
 ```

And that test will fail because of:

```
1) Ramsey\Collection\Test\CollectionManipulationTest::testDiffGenericCollection
TypeError: Argument 1 passed to Ramsey\Collection\Collection::__construct() must be of the type string, array given, called in collection\src\AbstractCollection.php on line 294
```

Yes, because inside of `AbstractCollection` 294 we have this:

```
return new static(array_merge($diffAtoB, $diffBtoA));
```

## Expected behavior

I expect that type of collection will be saved and this test case should pass.
I expect something like this:

```php
<?php
        if (static::class === Collection::class) {
            return new static(static::getType(), array_merge($diffAtoB, $diffBtoA));
        }

 return new static(array_merge($diffAtoB, $diffBtoA));
```
Maybe I'm wrong, but Generic collections should also be able to support
diff, intersect, merge etc. methods.

## Environment details

 - OS: Win 10
 - PHP 7.4
 - ramsey/collection version: 1.0.1

### PR DESCRIPTION
**Pull request by SimoTod**
The three methods above don't work with generic Collections since they use a constructor with only one argument (e.g. `new static($data);`) while `Collection.php` needs 2 arguments (type and data set);

## Description
Instead of instantiating a new object, we create a shallow copy of the original class using clone as we already do for filter, sort, etc and we update the copy to point to the new dataset.

## Motivation and Context
Using those methods with generic collection triggers an unhandled exception (`TypeError: Argument 1 passed to Ramsey\Collection\Collection::__construct() must be of the type string, array given`) but there's no mention of it in either the documentation or the docblocks.
Closes #53 

## How Has This Been Tested?
I've added 6 new unit tests to cover those changes. Before the patch, those tests were failing as expected; after the patch, they passes.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I ran `composer test` locally and there were no failures or errors.

### CODE REVIEW

**Comment by SimoTod** [comment]
Hi @ramsey ,
sorry to bother you. Do you think you would consider this fix? I'm happy to close this PR and use/maintain my own fork if you think the library doesn't need it.
Thanks for your time.

**Comment by ramsey** [comment]
Please leave it open. I haven’t had time to get to it, but I’ll try to review soon. Thanks!

**Comment by SimoTod** [comment]
Hi @ramsey 
do you have any updates on my pending PRs? (sorry, I don't like to tag maintainers but they've been open for a while)
I'm also happy to maintain this repo if you don't have time or you don't want to support it anymore either under your namespace or a separate fork. Also happy to close these 3 PRs if you don't want to merge them (In that case, I'll do tag a release from my own fork and update my readme to mention that it's based on your library).

Thanks,
Simone

**Comment by ramsey** [comment]
Thanks for the reminder. I'll try to look at them today. 🙂

**Comment by diwms** [comment]
I'm very happy that Simone has fixed my issue.
Basically I have a few projects with `own` fixes using patches...
I'd like to have just an updated version in my composer.json and get rid of this workarounds 👍🏻 

@ramsey could you please make the final decision about this PR (and my issue as well)?
I know, Open Source isn't something about annoying the maintainer, but my issue here from February :(

We really wanna make this package better and help with everything we can!
I know how it's hard to maintain a package when OSS isn't a full time paid job.

But we are here to help!

**Comment by ramsey** [comment]
Thank you for contributing! 🎉

**Pull request merged**
