### PR TITLE
Feature error messages

### PR DESCRIPTION
**Pull request by eclipxe13**
Create `ValueToStringTrait::toolValueToString` to cast values to strings, useful to produce error messages on `AbstractCollection` and `NamedParameterMap`. This help to create better error messages and avoid php errors when add an object as a value of a NamedParameterMap object.

### CODE REVIEW

**Comment by eclipxe13** [comment]
uhm... I see why CI is failing, looks like in hhvm you cannot declare `__toString()` but public, I create this test because I was using `method_exists` instead of `is_callable`. I think I should remove this test and class as seems to be unnecessary.

**Comment by eclipxe13** [comment]
(flip table) more hhvm errors... will improve test and try under hhvm before push

**Comment by ramsey** [comment]
No worries. Could it be failing because the test name is misspelled as "ValueToStringTraintTest?"

Also, please make sure your files end with a newline character.

**Comment by ramsey** [comment]
The changes look good. Just make sure your files (even test classes) end with a trailing newline character. I don't currently have Travis CI set up to run `phpcs` on the `tests/` directory, but I do for all my other projects, so if I add it here, the tests will fail, since PSR-2 requires a newline at the end of files.

Thanks for all this work. Looks great!

**Comment by ramsey** [comment]
Thanks!

**Pull request merged**
