### PR TITLE
Test against php 8.1

### PR DESCRIPTION
**Pull request by sergiy-petrov**

### CODE REVIEW

**Comment by SimoTod** [comment]
@sergiy-petrov https://github.com/ramsey/collection/runs/3852160969?check_suite_focus=true for example.
It's further down in the same yml file

**Comment by ramsey** [comment]
If you want to get rid of the `include:` section entirely, that should be fine.

**Comment by sergiy-petrov** [comment]
@SimoTod oh sorry, I see what you mean now.

@ramsey I've removed include section

**Comment by ramsey** [comment]
Thank you for contributing! 🎉

**Pull request merged**
